//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1240.0 using the following command:
// xscgen -v --ca -n urn:oasis:names:tc:xliff:document:2.0=Lingo.Core.Formats.Xliff.V20 -n http://www.w3.org/XML/1998/namespace=Lingo.Core.Formats.Xliff.V20.W3C -o Lingo.Core/Formats/Xliff/v20 Lingo.Core/Formats/Xliff/v20/xliff_core_2.0.xsd https://www.w3.org/2001/xml.xsd
namespace Lingo.Core.Formats.Xliff.V20.W3C
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("space", Namespace="http://www.w3.org/XML/1998/namespace", AnonymousType=true)]
    public enum Space
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("default")]
        Default,
        
        [System.Xml.Serialization.XmlEnumAttribute("preserve")]
        Preserve,
    }
}
